version: '2'

volumes:
  db_data: {}

services:

  db:
    container_name: database-mysql-5.7
    build:
      context: ./docker/db/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hereswhatsontap
      MYSQL_USER: hereswhatsontap
      MYSQL_PASSWORD: hereswhatsontap!
    ports:
      - "3321:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    container_name: apache-symfony-4
    build:
      context: ./docker/web/
    image: php
    ports:
      - "8021:80"
      - "9000"
    volumes:
      - ./app/:/var/www/symfony
    environment:
      XDEBUG_CONFIG: remote_host=10.254.254.254