version: "2"

services:

   apache:
     build: php-7.2
     container_name: apache
     build:
      context: ./docker/web/
     ports:
       - "8080:80"
     restart: always
     volumes:
         - ${SYMFONY_PATH}:/var/www/app
     # https://stackoverflow.com/questions/37100358/docker-composer-exited-with-code-0
     tty: true
     depends_on:
       - db
     environment:
           XDEBUG_CONFIG: remote_host=10.254.254.254

   db:
     image: mysql:5.7
     container_name: mysql
     build:
       context: ./docker/db/
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
       MYSQL_DATABASE: ${SYMFONY_DB_NAME}
       MYSQL_USER: ${SYMFONY_DB_USER}
       MYSQL_PASSWORD: ${SYMFONY_DB_PASS}
     ports:
         - "3307:3306"

volumes:
    db_data: